.eslintrc.json, .gitignore, _types/global.d.ts, manifest.ts, package.json, src/lib/index.ts, src/lib/listeners.ts, src/lib/messageUtils.ts, src/pages/background/index.ts, src/pages/popup/Popup.tsx, tsconfig.json, utils/manifest-parser/index.ts, utils/plugins/custom-dynamic-import.ts, utils/plugins/make-manifest.ts, utils/reload/initReloadServer.js, utils/reload/injections/script.js, utils/reload/injections/script.ts, utils/reload/injections/view.js, vite.config.ts, yarn.lock
- added extension updates to run on Firefox
- update dynamic imports for Firefox
- add browser API check for older FF versions (no need for external polyfill)
- overall code improvements
=> Firefox support

yarn.lock
Fresh yarn install and cache clean to refresh yarn.lock to improve dependabot
=> Clean yarn cache and install fresh on node 16.19.0

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .prettierignore, README.md
added code of conduct, contribution guides, updated readme with contribution section, configured prettierignore
=> chore: added code of conduct, contribution guide, updated readme

.github/workflows/pr-title-check.yml
=> chore: check for conventional commit PR title

.github/labeler.yml, .github/workflows/labels.yml
=> chore(ci): add labeler action

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/PULL_REQUEST_TEMPLATE.md
=> chore: add issue and pr templates

src/background/Background.ts, src/background/index.ts, src/background/installHandlers.ts, src/utils/storage.ts
=> chore: Storage wrapper

src/background/services/monetization.ts
=> feat(background): check WM state when receiving messages (temp)

src/background/utils.ts
=> feat(background): recurring interval

src/popup/components/ConnectWalletForm.tsx
=> feat: Remove text from popup

scripts/build.ts, scripts/dev.ts, scripts/profiler.ts, src/content/services/contentScript.ts, webpack/config.ts
Whenever a build occurred, Webpack was not reporting the errors.
=> chore(webpack): report errors when build fails

src/background/services/background.ts, src/background/services/monetization.ts, src/shared/types.ts
=> feat: pause monetization when losing window focus

src/popup/components/ConnectWalletForm.tsx, src/popup/components/PayWebsiteForm.tsx, src/popup/components/WalletInformation.tsx, src/popup/lib/utils.test.ts, src/popup/lib/utils.ts, src/popup/pages/Home.tsx
=> feat: Number format for rate of pay

src/background/services/background.ts, src/background/services/events.ts, src/background/services/monetization.ts, src/background/services/paymentSession.ts, src/background/services/storage.ts, src/background/services/tabEvents.ts, src/shared/helpers.ts, src/shared/types.ts, tsconfig.json
=> feat: adjust monetization frequency based on wallet

package.json, pnpm-lock.yaml
This reverts commit 09561225f07b5f5f09fdbe7b83a7f0f2558657a5.
Reverts #275.
=> chore: revert "chore(deps): update dependency eslint to v9"

src/background/services/monetization.ts, src/content/services/frameManager.ts, src/content/services/monetizationTagManager.ts, src/shared/messages.ts
=> feat: Bulk actions start, stop, resume

src/background/services/tabEvents.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/355
Just couldn't resist.
Also, keeping thing MV3 only now (only `browser.action` now, no `browserAction`).
=> refactor(background): clear up icons usage

src/_locales/en/messages.json, src/background/services/tabEvents.ts
Closes https://github.com/interledger/web-monetization-extension/issues/354
Add monetization state to tooltip title.
=> feat: add monetization state to browser action's tooltip text

src/background/services/openPayments.ts, src/background/services/paymentSession.ts, src/shared/types.ts
=> feat(background): remove quoting

README.md
We do not have the `static` folder anymore.
=> docs(README): update project structure section

README.md
=> docs(README): mention nvm windows

.github/labeler.yml, src/_locales/en/messages.json, src/background/services/openPayments.ts, src/background/services/tabEvents.ts, src/popup/components/SiteNotMonetized.tsx, src/popup/pages/MissingHostPermission.tsx
As discussed in https://github.com/interledger/web-monetization-extension/pull/366#discussion_r1677606933
=> refactor(locales): update keys to be more consistent

src/background/services/openPayments.ts, src/background/services/paymentSession.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/428
Can reuse error detection now.
=> refactor(background): move OP error detection to openPayments

src/popup/components/ConnectWalletForm.tsx, src/popup/pages/Settings.tsx
We were doing `import { connected } from 'process'` 😬
=> fix(popup): remove stray import of `connected` from `node:process`

src/_locales/en/messages.json, src/background/services/monetization.ts, src/background/services/openPayments.ts, src/background/services/paymentSession.ts
- Closes https://github.com/interledger/web-monetization-extension/issues/387
- Part of https://github.com/interledger/web-monetization-extension/issues/147
- Use `isOutOfFundsError` (extracted from https://github.com/interledger/web-monetization-extension/pull/426)
- Refactor code a bit.
=> fix(background): detect out-of-funds on Pay now button

src/background/container.ts, src/background/services/background.ts, src/background/services/monetization.ts, src/background/services/paymentSession.ts
- Closes #460
- Closes https://github.com/interledger/web-monetization-extension/issues/468
- Ensure not to trigger extra/unnecessary/stray payments on focus change
- Don't use `await sleep()`, but clear timers/intervals on stop. `sleep` and related state management leads to race conditions and stray runs.
- Don't resend overpaying (existing) monetization event on disable/enable and on focus change
=> fix(background): don't create unncessary payments & events

src/content/services/monetizationTagManager.ts
=> fix(content): do not monetize during prerendering

package.json, pnpm-lock.yaml
=> chore(deps): remove react-number-format (as unused)

package.json, src/_locales/en/messages.json, src/manifest.json
=> chore: update manifest for preview

src/_locales/en/messages.json
=> chore: update extension name

src/content/services/frameManager.ts
Fixes https://github.com/interledger/web-monetization-extension/issues/493
Regressed in https://github.com/interledger/web-monetization-extension/pull/464 as we removed the safety check for `event.stopPropagation()` there.
=> fix(content): listen only to extension messages to avoid sites break

src/background/container.ts, src/background/services/background.ts, src/background/services/deduplicator.ts, src/background/services/heartbeat.ts, src/background/services/monetization.ts, src/background/services/openPayments.ts, src/background/services/sendToPopup.ts, src/background/services/storage.ts, src/background/services/tabEvents.ts, src/background/services/tabState.ts, src/content/container.ts, src/content/services/contentScript.ts, src/content/services/frameManager.ts, src/content/services/monetizationTagManager.ts, webpack/prod.ts
Closes #497.
Switching to `PROXY`, will allow us to do mangling during minification.
=> refactor: switch Awilix container injection mode to proxy

.github/workflows/pr-title-check.yml, cspell-dictionary.txt
=> chore(actions): run title check on PR change

.github/workflows/pr-checks.yml
Closes https://github.com/interledger/web-monetization-extension/pull/183
Extracted from https://github.com/interledger/web-monetization-extension/pull/509
Done during pair-programming
=> chore(ci): avoid double-zip in build previews; update action

README.md
=> chore: update readme - project structure

.git-blame-ignore-revs
https://github.com/interledger/web-monetization-extension/pull/539#issuecomment-2309773391
=> chore: create `.git-blame-ignore-revs`

.github/workflows/nightly-build.yaml
Sometimes, nightly release was getting marked as draft. Draft releases are visible only to maintainers. 
Reason for why release was marked draft unknown, won't invest too much effort in 3rd party GitHub Actions.
Add another step to ensure that the release is published, not marked as draft. This step won't fail if re-run on published release.
=> fix(ci/nightly): ensure release is published

src/popup/components/ui/Input.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/559
Part of https://github.com/interledger/web-monetization-extension/issues/565
| Before | After |
| --- | --- |
| ![before](https://github.com/user-attachments/assets/8fad986e-93fe-4f75-a409-c9ddb16ed256) | ![after](https://github.com/user-attachments/assets/56b1c96c-e167-4b52-94eb-a6e944057447) |
=> fix(popup/Input): use correct lighter color for placeholder

src/background/services/tabEvents.ts
Now we only pass browser via awilix container.
=> refactor(background/tabEvents): remove `browser` import

src/background/services/openPayments.ts, src/shared/helpers.test.ts, src/shared/helpers.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/630
Reduced nesting in code. View diff with ignore-whitespace.
=> refactor(bg/openPayments): use `Promise.withResolvers`

esbuild/dev.ts
Related to https://github.com/interledger/web-monetization-extension/issues/418, but only for dev.
Avoids need to manually reload every time there's change in content scripts or background (which reloads extension, hence content scripts).
=> chore(scripts/dev): reload page on content script change

tests/e2e/basic.spec.ts, tests/e2e/connect.spec.ts, tests/e2e/connectAutoKeyTestWallet.spec.ts, tests/e2e/fixtures/connected.ts, tests/e2e/helpers/testWallet.ts, tests/e2e/pages/popup.ts
Labels/text changed and we forgot to update E2E tests. Maybe we should run these on each PR also?
=> test(e2e): use labels with i18n, don't hardcode

src/content/keyAutoAdd/lib/helpers.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/643
=> refactor(content/keyAutoAdd): improve timeout handling

src/background/services/keyAutoAdd.ts, src/shared/helpers.ts, tests/e2e/connectAutoKeyTestWallet.spec.ts, tests/e2e/helpers/common.ts, tests/e2e/helpers/testWallet.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/643
=> refactor: extract some common helpers

src/popup/components/ConnectWalletForm.tsx, src/popup/components/InputAmount.tsx, src/shared/helpers.ts
Making it reusable for https://github.com/interledger/web-monetization-extension/pull/657 and https://github.com/interledger/web-monetization-extension/pull/658.
=> refactor(popup): extract InputAmount from ConnectWalletForm

tests/e2e/simple.spec.ts
Missed in https://github.com/interledger/web-monetization-extension/pull/658
=> test(e2e/simple): update to reflect no slider on home-page

src/popup/components/ConnectWalletForm.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/679
=> fix(popup/ConnectWalletForm): make it centered in popup

src/popup/pages/Home.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/680
=> fix(popup/Home): unlink from "click on settings"

src/popup/components/InputAmount.tsx, src/shared/helpers.ts
Don't wait for input blur to validate.
=> fix(popup/InputAmount): validate amount on input, not just blur

src/popup/components/InputAmount.tsx
Now user can use arrow keys, `ctrl+a` etc. in the input.
=> fix(popup/InputAmount): don't be overly restrictive in keys allowed

src/popup/components/Settings/WalletInformation.tsx
Removing dependency as not that useful.
2 files left after this.
=> refactor(popup/WalletInformation): remove `react-hook-form`

package.json, pnpm-lock.yaml, src/popup/components/ErrorKeyRevoked.tsx
Remove `react-hook-form` last part.
🎉 Reduced 22KB from popup.js and 9KB from zip
=> refactor(popup/ErrorKeyRevoked): remove `react-hook-form`

src/popup/components/ConnectWalletForm.tsx, src/popup/components/InputAmount.tsx, src/popup/components/Settings/Budget.tsx, src/popup/components/ui/Input.tsx, src/popup/components/ui/__tests__/Input.tsx
https://github.com/interledger/web-monetization-extension/pull/736#discussion_r1863022736
- Add `trailingAddOn` prop
- Rename `addOn` to `leadingAddOn`, and remove `addOnPosition`
- Support `readOnly` prop correctly
=> feat(popup/Input): support `trailingAddOn`

src/popup/components/ConnectWalletForm.tsx, src/popup/components/ui/Input.tsx, tests/e2e/basic.spec.ts
https://github.com/interledger/web-monetization-extension/pull/736#issuecomment-2507500461
=> fix(ConnectWalletForm): don't disable inputs during validation

tests/e2e/auth.setup.ts
Helps us developers to ensure we've the key public key that we reference in `.env` added to test wallet for given wallet address.
=> test(e2e/setup): ensure given public key added to test wallet

.github/labeler.yml, cspell-dictionary.txt
This got outdated.
- Add new labels and patterns
- Remove top-level `any` (default) to reduce nesting.
=> chore(ci/labeler): update labeler config

.github/labeler.yml
Another baddie in https://github.com/interledger/web-monetization-extension/pull/762 🙈
=> chore(ci/labeler): fix pattern for documentation label

src/pages/popup/components/Settings/RateOfPay.tsx, src/pages/shared/components/InputAmount.tsx
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/efea1fd8-fc7a-4d54-94a7-27c481c61030)| ![image](https://github.com/user-attachments/assets/f0467cf3-ea34-412a-b1eb-2478be0e9ed6) |
Regressed in https://github.com/interledger/web-monetization-extension/pull/736
=> fix(popup/PayWebsiteForm): make amount input full width

src/background/services/keyAutoAdd.ts, src/manifest.json
Closes https://github.com/interledger/web-monetization-extension/issues/790
Remove "Extension" suffix from name for stores, but preserve in key auto-add nickname so extension is better identifiable there.
=> fix(manifest.json): remove "Extension" suffix from name

tests/e2e/env.d.ts, tests/e2e/helpers/common.ts
So that `monetizationCallback.calls[0][0].amountSent.value` as type `string`
Add types, only for E2E tests.
=> refactor(tests/e2e): add type for `MonetizationEvent`

src/background/services/keyAutoAdd.ts
Closes https://github.com/interledger/web-monetization-extension/issues/848
=> fix(bg/keyAutoAdd): activate only on tab opened for key addition

tests/e2e/connectAutoKeyChimoney.spec.ts
Chimoney changed things in sandbox, we can now complete the connect process without needing to send OTP.
=> test(e2e/connectAutoKeyChimoney): can finish connecting now

src/pages/popup/components/Settings/Budget.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/846
E2E tests pending on a rebase. Will send them as follow up. Working correctly locally.
=> fix(Settings/Budget): don't show renew message with one-time budget

.github/workflows/release-stable.yml, scripts/build.ts
Found just before stable release.
build script allowed passing invalid `--channel=release` when no target was specified.
=> fix(ci/release-stable): use `--channel=stable`

src/background/services/wallet.ts, src/pages/popup/components/OutOfFunds.tsx, src/pages/shared/components/ui/Input.tsx, tests/e2e/fixtures/helpers.ts, tests/e2e/out-of-funds.spec.ts, tests/e2e/pages/popup.ts
=> test(e2e): add tests for out of funds & add funds

src/background/services/background.ts, src/background/services/wallet.ts, src/pages/app/pages/PostInstall.tsx, src/pages/popup/pages/ConnectWallet.tsx, src/shared/messages.ts
Simplifying path towards https://github.com/interledger/web-monetization-extension/issues/844 and avoid confusing `CONNECT_WALLET` with null.
Add `RESET_CONNECT_STATE` message instead of calling `CONNECT_WALLET` with `null` payload.
=> refactor: use separate message to clear connect state

src/pages/popup/components/PayWebsiteForm.tsx
E2E tests flaky due to a regression from https://github.com/interledger/web-monetization-extension/pull/961
=> fix(PayWebsiteForm): don't render alert until needed

tests/e2e/connectAutoKeyChimoney.spec.ts
See https://github.com/interledger/web-monetization-extension/issues/972
=> test(e2e): temporarily disable Chimoney tests

docs/testing/testplan.md, src/pages/app/pages/PostInstall.tsx, src/pages/popup/components/ConnectWalletForm.tsx, src/pages/shared/components/AutoKeyAddConsent.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/676
=> fix: update links to docs

src/pages/popup/Popup.tsx
Missed in https://github.com/interledger/web-monetization-extension/pull/996 🤦🏽
=> fix(popup): fix incorrect route component

src/content/keyAutoAdd/lib/helpers/gatehub.ts, src/pages/app/pages/PostInstall.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/632
- Enable GateHub in PostInstall supported wallet list
- Update wallet address to have currency in lowercase
=> feat(PostInstall): list GateHub as supported wallet

tests/e2e/connectAutoKeyChimoney.spec.ts
Closes https://github.com/interledger/web-monetization-extension/issues/972
Revert https://github.com/interledger/web-monetization-extension/pull/973
=> test(e2e): re-enable Chimoney tests

src/content/__tests__/monetizationLinkManager.test.ts, src/content/services/monetizationLinkManager.ts, src/shared/__tests__/helpers.test.ts, src/shared/helpers/misc.ts
- Part of https://github.com/interledger/web-monetization-extension/issues/976
- Closes https://github.com/interledger/web-monetization-extension/issues/842
- Closes https://github.com/interledger/web-monetization-extension/issues/920
- Closes https://github.com/interledger/web-monetization-extension/pull/922 (supersedes)
- Monetize all links in iframes as well, including from body.
- Update tests (remove some about special iframe behavior too)
Will add e2e tests involving iframes as a follow up.
=> feat(linkManager): monetize all links in iframe, simplify detection
