interledger/web-monetization-extension

- src/popup/Popup.tsx
- src/providers/__tests__/popup-context.test.tsx
- src/providers/index.ts
- src/providers/popup-context.tsx
- src/providers/providers.interface.ts
- tsconfig.json
- webpack.config.utils.ts
Closes #59 
- add provider wrapper with context data
- add unit tests
> feat: Popup Context

- src/components/__tests__/code.test.tsx
- src/components/button.tsx
- src/components/code.tsx
- src/components/icons.tsx
- src/popup/index.css
- tailwind.config.ts
Closes #94.
Introduces a `Code` container to display the public key, with a copy button, allowing users to easily copy the value directly from the container.
> feat: add code container

- src/components/layout/header.tsx
- src/components/layout/main-layout.tsx
- src/components/slider.tsx
- src/popup/Popup.scss
- src/popup/index.html
- src/popup/pages/Home.tsx
- src/popup/pages/Settings.tsx
Closes #101 
- implement active page ui
- sync storage keys with the form data
- remove unused code
> feat: Active WebMo Page UI

- src/content/static/polyfill.ts
Closes #110 .
When modifying a document on Google Docs, one of the scripts attempts to declare a variable named `dbg`, which we have already initialized in the polyfill. This PR removes the `dbg` variable from the polyfill.
> chore: remove `dbg` from polyfill

- src/background/services/storage.ts
- src/popup/lib/context.tsx
- src/shared/types.ts
Closes #173, #108.
Initially, we attempted to reset the values by changing them back to `undefined` when clearing the storage, but this approach didn't actually change their values. We need to set them as `null` to properly clear the storage.
> fix: clear extension storage when disconnecting the wallet

- src/popup/pages/Home.tsx
- src/shared/helpers.ts
Saw a TODO in code, decided to clear it.
Adds a `debounceAsync` helper and use it. Doesn't debounce `onRateChange` as we want UI to be updated smoothly. Can probably add a 30ms debounce on it, but I think not needed.
[Screencast from 16-05-24 07:31:07 PM IST.webm](https://github.com/interledger/web-monetization-extension/assets/8426945/8afc4d7e-a404-4f43-9fc9-cdbe17056b75)
Demo has timeout set to 1500ms
> perf(popup/Home): debounce setting rate of pay

- src/background/services/storage.ts
On clicking disconnect, as we clear the storage, the popup shows the permission prompt again, even if we have the permissions.
Set default state to `true`, so popup doesn't show permission prompt. We'll ask again if we don't have permissions after popup opens again.
> fix(background/storage): set default `hasHostPermissions` to true

- src/background/services/background.ts
- src/popup/components/ProtectedRoute.tsx
Fixes https://github.com/interledger/web-monetization-extension/issues/330
Race condition and an unseen check on the conditions for when we populate storage.
Now, we call `storage.setHostPermissionStatus` only after `storage.populate` is called.
> fix(background): ensure default storage is populated; fix popup crash

- src/background/services/background.ts
- src/background/services/tabEvents.ts
- src/content/lib/messages.ts
- src/content/services/monetizationTagManager.ts
Closes https://github.com/interledger/web-monetization-extension/issues/329.
- We were not sending `IS_FRAME_MONETIZED` due to a premature optimization (not sending it when no tags), so we weren't updating the state when required.
- Also had some timing issues with not `await`-ing.
- We now use `sender.tab.id` to ensure we set the icon for the right tab, and not override it from a stale message from a different tab (race condition).
As discussed in call today, in future we'll try to make use of a `TabStateService` and use that as source of truth, and reduce reliance on message passing.
> fix: ensure correct icon is reflected for monetization state

- src/content/services/monetizationTagManager.ts
- src/content/utils.ts
Closes #365.
Initially I thought there was an error and the `load` event was not correctly dispatched. It looks like we omitted this. Now we dispatch the `load` event if the wallet address is valid.
Additional changes:
- small refactoring for the wallet address check
- update the `checkWalletAddressUrlFormat` function since we do not need to check for SPSP endpoints
> fix(content): dispatch `load` event if wallet address is valid

- src/background/services/events.ts
`super.once()` ends up using our deprecated panic-inducing `removeListener()`
Let `once()` work like it should. Keep the deprecation message in TypeScript only.
`addEventListener` still can throw.
> fix(background/events): don't throw on calling `once()`

- src/background/services/openPayments.ts
- src/background/services/storage.ts
- src/shared/helpers.ts
Closes #272.
Saves `grantSpentDebitAmount` as "amountSpent" in storage, which we can later use to retrieve balance. To handle race conditions, we store the max of amount spent in the batch of multiple (possibly parallel) calls.
Extracted from https://github.com/interledger/web-monetization-extension/pull/379, but using throttling instead of debouncing.
> feat(background): store spent amount on payment to retrieve balance

- src/background/services/storage.ts
- src/popup/components/ProtectedRoute.tsx
- src/shared/helpers.test.ts
- src/shared/helpers.ts
- src/shared/types.ts
Closes https://github.com/interledger/web-monetization-extension/issues/392
> fix(background/storage): allow extension be in multiple states

- .eslintrc.json
- cspell.json
- src/background/container.ts
- src/background/services/tabEvents.ts
- src/popup/Popup.tsx
- src/popup/components/SiteNotMonetized.tsx
- src/popup/lib/context.tsx
- src/popup/pages/MissingHostPermission.tsx
- src/shared/helpers.ts
- src/shared/types.ts
Making translations easier to use.
Adds following helpers: 
- `t(key, optionalSubsitutions)` added to background container
- as a shorter call over `this.browser.i18n.getMessage(key, optionalSubsitutions)`,
- where TypeScript ensures `key` exists in _locales
- For popup, a `const t = useTranslation()` helper.
- In popup, reduces place where we need to `import browser from 'webextension-polyfill'`, make it easier to test. The context default just returns passed key as is.
> refactor: add `t`, `useTranslation` helpers to use translations

- src/_locales/en/messages.json
- src/background/services/openPayments.ts
- tsconfig.json
Part of https://github.com/interledger/web-monetization-extension/issues/147
> fix(background): better error message for `connectWallet`

- src/popup/Popup.tsx
- src/popup/components/layout/header.tsx
- src/popup/lib/context.tsx
- src/popup/pages/MissingHostPermission.tsx
https://github.com/interledger/web-monetization-extension/pull/395#issuecomment-2210951743
> refactor(popup): add `useBrowser` hook; avoid importing everywhere

- src/content/services/frameManager.ts
- src/content/services/monetizationTagManager.ts
Prevents slow-down due to too many `IS_TAB_MONETIZED` events.
Adds back some of optimizations removed in https://github.com/interledger/web-monetization-extension/pull/355. Turns out, we we can use them correctly with start/end; just resume one was buggy.
Adds a little optimization in how we compute payload for `isTabMonetized` (more short-circuiting).
> fix(content): reduce amount of `IS_TAB_MONETIZED` messages/events

- src/background/services/openPayments.ts
Since quoting was removed in https://github.com/interledger/web-monetization-extension/pull/371, I constantly see timed out requests. The reason: under the hood, Rafiki still performs a quote, but we do not make the HTTP call. Since the quoting is still performed, some of the requests are timing out if it takes them more than 5 seconds to complete.
> fix(background): increase request timeout for the OP SDK

- src/background/services/paymentSession.ts
- src/background/services/tabState.ts
- src/content/polyfill.ts
- src/content/services/monetizationTagManager.ts
- src/shared/messages.ts
Closes #422.
- Changed `MonetizationEventPayload`: `detail` -> `details`
- Updated `tabState` methods to store the monetization event as well.
- Session now sends the last monetization event when starting an overpaying payment session
> feat(background): resend last monetization event on reload when overpaying

- src/popup/components/ConnectWalletForm.tsx
- src/popup/lib/utils.test.ts
- src/popup/lib/utils.ts
Closes #411.
Discussed during WM Work Week. ASEs can decide what term they want to use - wallet address or payment pointer. This PR allows the use of the short form ($ notation) in the popup.
> feat(popup): allow short form for wallet addresses in popup

- .eslintrc.json
- src/background/services/monetization.ts
- src/background/services/paymentSession.ts
- src/background/utils.ts
Part of https://github.com/interledger/web-monetization-extension/issues/394
- probe even with same currency
- ensure not to skip previous probing amount if temporarily failed to probe
> fix(background): probe even with same currency

- src/background/services/heartbeat.ts
Closes https://github.com/interledger/web-monetization-extension/issues/492
Pair programmed with @raducristianpopa and @sidvishnoi
> fix(background/Heartbeat): use `alarm` instead of `storage.set`

- src/background/services/background.ts
- src/background/services/tabEvents.ts
> fix(background): if wallet not connected, display default icon

- .github/actions/get-built-version.cjs
- .github/actions/setup/action.yml
- .github/workflows/nightly-build.yaml
- cspell-dictionary.txt
- esbuild/prod.ts
- package.json
- pnpm-lock.yaml
- src/manifest.json
Part of https://github.com/interledger/web-monetization-extension/pull/508
- Add nightly builds Mon-Sat 12AM UTC
- Update build script to generate correct zip names
> feat(ci): add nightly builds, rename zips

- .github/actions/get-built-version.cjs
- .github/workflows/nightly-build.yaml
Action failed: https://github.com/interledger/web-monetization-extension/actions/runs/10467680589/job/28986952428
Done during pair-programming.
- Update manifest file path
- Update release body
> chore(ci): fix manifest path in get-built-version action

- src/background/services/openPayments.ts
> fix(background): use correct intent in `completeGrant` for add funds

- src/popup/lib/context.tsx
- src/popup/pages/ErrorKeyRevoked.tsx
- src/popup/pages/Home.tsx
Remove `ReducerActionType` enum, replace with inline, like we do in rest of the code.
> refactor(popup): use reducer/dispatch consistently

- src/popup/components/ConnectWalletForm.tsx
- src/popup/pages/Settings.tsx
https://github.com/interledger/web-monetization-extension/issues/565 introduces some more validation. So simplifying this component to make it more testable.
- Remove this component's reliance on `localStorage` (replace with `defaultValues` and `onChange` props).
- Remove reliance from `browser.runtime.sendMessage`/`useMessage` (replace with `connectWallet` prop)
- Remove reliance on `fetch`/`getWalletInformation` (replace with `getWalletInfo` prop)
- Trigger saving to local storage onBlur instead of onChange with debounce (tested Linux/Mac Chrome/Firefox combo)
- Prefix localStorage keys with `connect.`
> refactor(popup/ConnectWalletForm): reduce reliance on browser APIs

- .github/workflows/nightly-build.yaml
- .github/workflows/tests-e2e.yml
- docs/TESTING.md
- package.json
- tests/e2e/.env.example
- tests/e2e/fixtures/helpers.ts
Discovered somehow 😆 
`PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1` lets us use headless with extensions.
> test(e2e): support running in headless mode

- .github/workflows/tests-e2e.yml
If someone added any unrelated review, existing test run got cancelled. Not anymore.
Context: https://github.com/interledger/web-monetization-extension/actions/runs/10885243656
> fix(ci/test-e2e): don't cancel in-progress jobs

- playwright.config.ts
With the current setup, if the first run fails we are not saving the trace for it, only for the first retry.
Retain traces only for failed runs.
> test(e2e): retain traces for failed runs

- src/background/services/tabEvents.ts
- src/background/services/tabState.ts
In Chrome, we get 3 fetch requests on each `setIcon` calls even if setting same icon. Each request takes 5-25ms, which is unnecessary and noisy as well.
> perf(background/tabEvents): memoize `setIcon` call

- src/background/services/background.ts
- src/popup/lib/context.tsx
- src/shared/helpers.ts
- src/shared/messages.ts
Closes https://github.com/interledger/web-monetization-extension/issues/620
Extracted from https://github.com/interledger/web-monetization-extension/pull/619 (check out usage in [`addPublicKeyToWallet`](https://github.com/interledger/web-monetization-extension/blob/ca775a201a846189618fbd35539cfb283481fb05/src/background/services/openPayments.ts#L507-L509) + [its handler](https://github.com/interledger/web-monetization-extension/blob/ca775a201a846189618fbd35539cfb283481fb05/src/popup/components/ConnectWalletForm.tsx#L134-L137); also in [`ConnectWalletForm` validation handler](https://github.com/interledger/web-monetization-extension/blob/ca775a201a846189618fbd35539cfb283481fb05/src/popup/components/ConnectWalletForm.tsx#L247-L248))
- Introduces following helpers:
- `ErrorWithKey` (extends …
> refactor: introduce `ErrorWithKey` (locales keys as error code)

- src/background/container.ts
- src/background/services/background.ts
- src/background/services/index.ts
- src/background/services/monetization.ts
- src/background/services/tabEvents.ts
- src/background/services/windowState.ts
- src/background/utils.ts
- src/content/services/contentScript.ts
- src/content/services/monetizationLinkManager.ts
- src/shared/helpers.ts
- src/shared/messages.ts
- src/shared/types.ts
Closes https://github.com/interledger/web-monetization-extension/issues/67
Why:
- In Edge, `browser.tabs.query()` skips tabs in right-pane of split-view, as if it don't exist. So, we need to keep track of existing tabs in a window ourselves.
- Similarly, we can't know which tab was last focused.
- There's no API to tell which all tabs are visible (that can be monetized) in a Edge split-view or Vivaldi tab-tiling view.
- Fire a `TAB_FOCUSED` event from content script, on load (if focused) and on focus change (if focused).
- Use the `sender.tab.id` from above event to store last focused tabId for given window.
- Store that info in newly added `WindowState` service.
- Also store last focused window in above service.
- Note: Both pages in split-mode are monetized together.
- For Edge, if we …
> feat: support split-view in Edge, tab-tiling in Vivaldi

- src/background/constants.ts
- src/background/services/background.ts
- src/background/services/monetization.ts
- src/background/services/tabEvents.ts
- src/background/services/tabState.ts
- src/background/utils.ts
- src/popup/components/PayWebsiteForm.tsx
- src/popup/lib/context.tsx
- src/popup/pages/Home.tsx
- src/shared/messages.ts
- src/shared/types.ts
- Closes https://github.com/interledger/web-monetization-extension/issues/560
- Will help with https://github.com/interledger/web-monetization-extension/issues/584
- refactor(PopupState): add all popup data related to tab under `tab`
- `tabUrl` -> `tab.url`
- `isSiteMonetized` -> `tab.status === 'monetized'`
- `hasAllSessionsInvalid` -> `tab.status === 'all_sessions_invalid'`
- refactor(monetization): extract `getPopupTabData` to tabState service
- refactor(tabEvents): use `getPopupTabData` instead of multiple params
Paves way to show more useful messages with `tab.status` (e.g. new tab, internal extension pages, non-https pages)
> fix: update popup tab data along with icon

- src/background/services/openPayments.ts
Reject if user closes tab before accepting. Prevent leaving a dangling tab watcher.
Rejection not need to be handled at the moment, but will be handled as a part of https://github.com/interledger/web-monetization-extension/issues/626 so we can show user any errors or progress as needed.
> fix(bg/openPayments): handle tab close before accept

- src/content/services/monetizationLinkManager.ts
Visiting some sites that remove link tags on load (in this case Google calendar) led to following error in console:
```
Uncaught (in promise) Error: Could not find details for monetization node <link rel="icon" id="favicon" type="image/x-icon" href="https://calendar.google.com/googlecalendar/images/favicons_2020q4/calendar_1.ico">
at MonetizationLinkManager.onRemovedLink (content.js:3456:15)
at content.js:3347:39
at NodeList.forEach (<anonymous>)
at MonetizationLinkManager.onWholeDocumentObserved (content.js:3345:31)
```
Ignore removed link nodes that aren't relevant.
> fix(content): ignore non-monetization links when `<link>` removed

- README.md
- cspell-dictionary.txt
- esbuild/config.ts
- esbuild/dev.ts
- src/_locales/en/messages.json
- src/background/services/background.ts
- src/background/services/keyAutoAdd.ts
- src/background/services/keyShare.ts
- src/background/services/openPayments.ts
- src/content/keyAutoAdd/lib/helpers.ts
- src/content/keyAutoAdd/lib/keyAutoAdd.ts
- src/content/keyAutoAdd/lib/types.ts
- src/content/keyAutoAdd/testWallet.ts
- src/manifest.json
- src/popup/components/ConnectWalletForm.tsx
- src/popup/pages/Settings.tsx
- src/shared/helpers.ts
- src/shared/messages.ts
- src/shared/types.ts
- tests/e2e/basic.spec.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- tests/e2e/helpers/common.ts
- tests/e2e/helpers/testWallet.ts
- tests/e2e/pages/popup.ts
- Closes https://github.com/interledger/web-monetization-extension/issues/615
- Closes https://github.com/interledger/web-monetization-extension/issues/616
- Part of https://github.com/interledger/web-monetization-extension/issues/613
- Add new content script to automate key-addition to wallets.
- The scripts are in `content/keyAutoAdd/*`
- `content/keyAutoAdd/lib/*` contains script integration with background, along with some helper utils.
- These content scripts are injected only to specific wallet URLs, and not to all URLs.
- The content scripts are written as "steps" so we can track their breakage better, and show progress to user. Some steps can be marked as "skipped".
- `content/keyAutoAdd/testWallet.ts` contains a sample automation for the test wallet, via API reverse engineering. …
> feat: auto-add key to wallet, support for test wallet

- src/background/services/background.ts
- src/background/services/keyAutoAdd.ts
- src/background/services/openPayments.ts
- src/popup/components/ConnectWalletForm.tsx
- src/popup/pages/Settings.tsx
- src/shared/messages.ts
- src/shared/types.ts
Part of https://github.com/interledger/web-monetization-extension/issues/613
[Screencast from 02-10-24 05:45:59 PM IST.webm](https://github.com/user-attachments/assets/a6620bac-439a-4cfc-a6f0-15b4c243e900)
> fix(ConnectWalletForm): preserve errors on popup reopen

- src/content/keyAutoAdd/lib/keyAutoAdd.ts
- src/content/keyAutoAdd/lib/types.ts
- src/content/keyAutoAdd/testWallet.ts
Simplifies KeyAutoAdd's step runner to let us get output of any step (that has been previously run), not just result of previous. Getting result of previous had limitation that any intermediate steps had to pass through data from previous steps. Now we store outputs in a Map and get those with the `output(fn)` helper (WeakMap not needed, as we store reference to function anyway in steps array).
Also update signature of StepRun function.
Additionally, turn `skip` call to throw an instance of `SkipError` instead of object with symbol.
> fix(content/KeyAutoAdd): get output of any step, not just of previous

- src/popup/components/ConnectWalletForm.tsx
Earlier, we stored only localized message in `errors[foo]`. Now we preserve the `key` and original error under `{info}`; and add the localized message under `{message}`.
This will help with error handling based on key, and paves way to support retry add-key on retry-able errors (such as timed out waiting for login, wrong account was logged in, key-add consent accidentally declined etc.)
Part of https://github.com/interledger/web-monetization-extension/issues/613
> refactor(ConnectWalletForm): preserve key in errors

- src/background/services/background.ts
- src/background/services/keyAutoAdd.ts
- src/popup/components/ConnectWalletForm.tsx
- src/shared/helpers.ts
Support retry add-key on retry-able errors, such as timed out waiting for login, wrong account was logged in etc.
Also add a `cause` property on `ErrorWithKeyLike`.
Part of https://github.com/interledger/web-monetization-extension/issues/613
> feat(ConnectWalletForm): let retry key auto-add on some errors

- src/_locales/en/messages.json
- src/background/services/keyAutoAdd.ts
- src/background/services/openPayments.ts
- src/popup/components/ConnectWalletForm.tsx
- src/popup/pages/Settings.tsx
- src/shared/messages.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- Closes https://github.com/interledger/web-monetization-extension/issues/625
- Part of https://github.com/interledger/web-monetization-extension/issues/613
[Screencast from 02-10-24 09:22:43 PM IST.webm](https://github.com/user-attachments/assets/53317616-4608-4fc8-b7ca-16529a65159d)
> feat(ConnectWalletForm): ask consent for automatic key addition

- src/background/services/openPayments.ts
- src/content/keyAutoAdd/fynbos.ts
Instead of performing DOM actions, call the routes directly to upload the public key.
> fix: use network requests for auto-add key to Fynbos

- .github/workflows/nightly-build.yaml
- .github/workflows/tests-e2e.yml
- docs/TESTING.md
- tests/e2e/.env.example
- tests/e2e/auth.setup.ts
- tests/e2e/connect.spec.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- tests/e2e/env.d.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/simple.spec.ts
1. Add `TEST_WALLET_` prefix to test wallet related vars
2. Add types for `process.env`
3. Update location of .env file from tests/.env to tests/e2e/.env
> refactor(tests/e2e): rename environment variables

- src/popup/components/ConnectWalletForm.tsx
If we emptied the input, and then pasted something (for example, cut and paste), we weren't setting the input value (with `ev.preventDefault`). This was looking as if we pasted empty string in input (leading to "wallet address is required" error).
> fix(popup/ConnectWalletForm): fix paste after field is emptied

- src/pages/progress-connect/index.css
- src/popup/components/ui/Code.tsx
- src/popup/components/ui/Input.tsx
- src/popup/index.css
Live coded during discussion with Madalina today.
> fix(popup): make disabled inputs make look more disabled

- .github/workflows/bump-manifest-version.yml
As seen in https://github.com/interledger/web-monetization-extension/pull/687/commits/8cb6b85b8235861e5b6ce71d8cc3184fad1fd06b
> fix(ci/bump-manifest-version): format manifest.json after update

- .eslintignore
Was leading to too many errors in generated files.
> chore(.eslintignore): exclude playwright test results & reports

- package.json
- pnpm-lock.yaml
Reverts 2176a58fbd3d458e40018594119721471386dfc9
Was getting error `structured_headers_1.ByteSequence is not a constructor` on connect. Should've run E2E tests before merging #664
> chore(deps): revert update structured-headers to v2

- src/background/services/monetization.ts
- src/background/services/paymentSession.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/694
Will either throw or retry, but never return `undefined`.
> refactor(bg/PaymentSession): never return `undefined` from `pay()`

- src/popup/components/InputAmount.tsx
- src/popup/components/OutOfFunds.tsx
Removing `react-hook-form` dependency as not that useful.
Only KeyRevoked error screen left after this.
> refactor(OutOfFunds): remove `react-hook-form`, use `InputAmount`

- esbuild/config.ts
- esbuild/plugins.ts
The copy plugin should be able to copy all the files correctly, regardless of the operating system (Windows, Linux, or macOS).
Closes #711 .
Convert the backslashes to forward slashes in the from and to paths passed to the copy plugin.
> fix(scripts/build): use correct asset-copy paths on Windows 

- .eslintrc.json
As seen in https://github.com/interledger/web-monetization-extension/pull/719#issuecomment-2485243119.
- Now we scope plugin and rules, targeted to files.
- Removed some rules that were already part of "recommended" extends.
> chore(.eslintrc): scope plugins to files

- docs/TESTING.md
- tests/e2e/connectAutoKeyFynbos.spec.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- tests/e2e/helpers/common.ts
- tests/e2e/helpers/fynbos.ts
- tests/e2e/helpers/testWallet.ts
Only difference was in defaultWaitMs, which we now pass as parameter.
> refactor(tests/e2e): extract `getContinueWaitTime` helper

- tests/e2e/fixtures/helpers.ts
Closes https://github.com/interledger/web-monetization-extension/issues/735
Wait for SW to be activated. Should fix the flakiness on Linux CI and absolute-failures on MacOS.
> fix(tests/e2e): wait for ServiceWorker to be activated

- .github/labeler.yml
If only there was a linter when sending https://github.com/interledger/web-monetization-extension/pull/762.
Ref: https://github.com/actions/labeler?tab=readme-ov-file#match-object
CI fails as its using labeler.yml from main, not this branch. That's why didn't fail in https://github.com/interledger/web-monetization-extension/pull/762.
> chore(ci/labeler): fix typo

- cspell-dictionary.txt
- package.json
- pnpm-lock.yaml
- src/pages/popup/Popup.tsx
- src/pages/popup/components/ConnectWalletForm.tsx
- src/pages/popup/components/PayWebsiteForm.tsx
- src/pages/popup/components/ProtectedRoute.tsx
- src/pages/popup/components/Settings/Budget.tsx
- src/pages/popup/components/Settings/RateOfPay.tsx
- src/pages/popup/components/layout/Header.tsx
- src/pages/popup/index.tsx
- src/pages/popup/lib/context.tsx
- src/pages/popup/lib/store.ts
- src/pages/popup/pages/ConnectWallet.tsx
- src/pages/popup/pages/ErrorKeyRevoked.tsx
- src/pages/popup/pages/Home.tsx
- src/pages/popup/pages/OutOfFunds.tsx
- src/pages/popup/pages/OutOfFunds_AddFunds.tsx
- src/pages/popup/pages/Settings.tsx
- src/shared/messages.ts
- src/shared/types.ts
Uses valtio for better render performance, and moves state out of context into a store in file.
- Turn `PopupContextProvider` to `WaitForStateLoad` to initialize store.
- Keep `usePopupState` as helper, even though it won't return dispatch now (only readonly state will be returned)
- Move state related things from `context.tsx` to `store.tsx`.
- Improve performance of RateOfPay screen as a test (we had too many props, not enough state)
- Kept `dispatch` mechanism for actions to update state. We don't need to change this right away.
- Tried to keep PR as small as possible. Most files just ±N line changes.
Adds +3KB to zip and +6KB to popup.js
> refactor(popup): use valtio external store for state management

- tests/e2e/connectAutoKeyChimoney.spec.ts
- tests/e2e/fixtures/helpers.ts
Our tests relied on `waitForEvent('page')` but the page that gets used during connect process was already open (as we reuse post-install screen tab), so E2E tests started to fail.
So, auto-close that post-install tab to keep tests like before, add a comment why it's better to close the tab.
> test(e2e): auto close post-install tab to keep tests simpler

- src/pages/popup/components/ConnectWalletForm.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/746
Using `InputEvent` with `inputType` `insertReplacementText`. Tested works as intended in Firefox. We consider autocompleted input only if `ev.data` contains a well formed input.
In Chrome, autocomplete menu didn't appear for me. Someone please verify it works ok.
> fix(ConnectWalletForm): handle input autocomplete

- src/background/services/keyAutoAdd.ts
- src/background/services/openPayments.ts
- src/background/utils.ts
`this.browser.tabs.get()` can throw a synchronous error before returning a promise.
If `this.browser.tabs.get(tabId ?? -1)` throws a synchronous error before returning a promise (Promise.reject), the .catch() won’t catch it, as the error occurs before the promise is created.
Closes #778 
- use a `try-catch` block to handle  `browser.tabs.get` exception
> fix(background/KeyAutoAdd): invalid tabId in Firefox

- .eslintrc.json
- src/background/services/tabEvents.ts
- src/pages/popup/components/TogglePaymentsButton.tsx
- src/pages/popup/components/layout/Header.tsx
- src/pages/popup/pages/Home.tsx
Closes #787 .
- Removed the large power button on Home screen when disabled, display disable message only.
- Always showing the toggle button in Header.
- Show the default colored icon in toolbar, instead of disabled gray one.
> fix(Popup): update global payment toggle UI

- src/shared/types.ts
- tests/e2e/basic.spec.ts
- tests/e2e/connect.spec.ts
- tests/e2e/connectAutoKeyChimoney.spec.ts
- tests/e2e/connectAutoKeyFynbos.spec.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- tests/e2e/fixtures/base.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/fixtures/helpers.ts
Remove duplication in tests related to background's storage.
- Add custom matcher `toHaveStorage` for easy storage inspection in tests
- Add helper `getStorage` as a type-safe and simpler wrapper over `chrome.storage.keys.get`
- Update tests to use the custom matcher and helpers.
> refactor(tests/e2e): add `toHaveStorage` custom matcher & utils

- esbuild/plugins.ts
Remove `@interledger/openapi` from bundle as we don't make use of validations.
```diff
-   dist/chrome/background/background.js                     766.5kb
+   dist/chrome/background/background.js                     593.0kb
```
> perf(background): remove `@interledger/openapi` from bundle

- src/background/services/background.ts
- src/background/services/events.ts
- src/background/services/outgoingPaymentGrant.ts
- src/background/services/wallet.ts
Closes https://github.com/interledger/web-monetization-extension/issues/818
- Close popup right before adding public key (opens or navigates tab)
- Close popup right before getting interaction hash (opens or navigates tab)
- Rename `wallet.close_popup` event to `request_popup_close`.
> fix(background): close popup on right time

- biome.jsonc
- src/background/services/tabEvents.ts
- src/pages/popup/components/NotMonetized.tsx
- tests/e2e/special.spec.ts
Closes https://github.com/interledger/web-monetization-extension/issues/819
Part of https://github.com/interledger/web-monetization-extension/issues/610
Fix issue and add E2E tests to validate cause of https://github.com/interledger/web-monetization-extension/issues/819.
> fix(bg/tabEvents): don't clear sessions on iframe navigation

- tests/e2e/helpers/common.ts
- tests/e2e/reconnectAutoKeyTestWallet.spec.ts
- tests/e2e/simple.spec.ts
- tests/e2e/special.spec.ts
Part of https://github.com/interledger/web-monetization-extension/issues/610
As mentioned in https://github.com/interledger/web-monetization-extension/pull/835#discussion_r1917857341
Add `setupPlayground` helper which loads playground with wallet addresses added, and sets up `monetization` event listener spy (`monetizationCallback`).
> refactor(tests/e2e): add `setupPlayground` helper

- src/pages/popup/components/ConnectWalletForm.tsx
`state` in `ConnectWalletForm` is a valtio proxy. Running `t()` (via `toErrorInfo`) on it doesn't resolve proxies (`browser.i18n.getMessage` doesn't resolve substitutions), leading to popup showing message like following:
`deepClone` to resolve valtio proxies so `t()` works as intended.
> fix(ConnectWalletForm): correctly render error from transientState

- tests/e2e/fixtures/base.ts
- tests/e2e/reconnectAutoKeyTestWallet.spec.ts
Avoiding flaky custom implementations!
- Rewrite `toHaveBeenCalledTimes` and `toHaveBeenLastCalledWithMatching` with `expect.poll`
- Remove `wait` option from above matchers - as timeout acts as wait, and when needed, we can `page.waitForTimeout(wait)` as wait.
- Add a missing await in reconnect test.
- Fixed default message (for use with `.not` modifier)
> refactor(tests/e2e): simplify spy `toHaveBeenCalled` matchers

- playwright.config.ts
- src/background/services/tabEvents.ts
- tests/e2e/fixtures/base.ts
- tests/e2e/helpers/common.ts
- tests/e2e/overpaying.spec.ts
- tests/e2e/pages/popup.ts
- tests/e2e/special.spec.ts
Closes https://github.com/interledger/web-monetization-extension/issues/850
Reopens https://github.com/interledger/web-monetization-extension/issues/819
Part of #610
Revert #831, add tests for page reload, sessions & overpaying, mark tests that were fixed by #831 as failing.
> fix(background): clear sessions on page reload

- src/background/services/paymentSession.ts
- tsconfig.json
Closes https://github.com/interledger/web-monetization-extension/issues/375
- With continuous payments, don't wait for prev payment to complete before sending next payment, to ensure the correct time of payment is followed to keep rate of pay consistent
- Remove `interval` and use recursive timeout, as it'd allow dynamic "interval"
- Tested at `assetScale: 2` at $60 per hour rate (`await chrome.storage.local.set({rateOfPay: '6000'})`) and [3 payment sessions](https://webmonetization.org/play/?wa=https://ilp.interledger-test.dev/sid&wa=https://ilp.interledger-test.dev/sid-mxn-1&wa=https://ilp.interledger-test.dev/sid-usd-1)
- No performance regressions on test wallet. Outgoing payments take ~150-350ms, typically 200ms.
- ~Except there was some error once, and it sent hundreds on concurrent …
> fix(bg/PaymentSession): don't wait for previous payment

- tests/e2e/not-monetized.spec.ts
Part of https://github.com/interledger/web-monetization-extension/issues/610
> test(e2e): add tests for various not-monetized scenarios

- .github/workflows/nightly-build.yaml
- .github/workflows/tests-e2e.yml
- playwright.config.ts
- tests/e2e/fixtures/base.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/fixtures/helpers.ts
- tests/e2e/pages/popup.ts
Some times some tests hang for unknown (as of now) reasons. For example, if Chimoney auto-connect test hangs, it takes 1.5min in CI to know if it failed.
Fail fast. Will help in debugging which parts fail due to actual timeouts and which parts just fail _randomly_.
Also, found we were using browser versions globally installed in GitHub env. Now we install specific browser variants.
Some tests still flaky, will diagnose as follow up.
> test(e2e): make timeouts shorter, install browsers

- src/content/keyAutoAdd/testWallet.ts
Check for `https://ilp.interledger.cards/<wallet_address_name>` and `https://ilp.dev/<wallet_address_name>` at the same time.
There are collision issues since `ilp.dev` wallet addresses are just a proxy behind some of the `ilp.interledger.cards` wallet addresses.
> fix(keyAutoAdd/cards): normalize `ilp.dev` wallet addresses

- playwright.config.ts
- tests/e2e/connect.spec.ts
- tests/e2e/connectAutoKeyChimoney.spec.ts
- tests/e2e/fixtures/base.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/not-monetized.spec.ts
- tests/e2e/overpaying.spec.ts
- tests/e2e/simple.spec.ts
Closes https://github.com/interledger/web-monetization-extension/issues/873
Playwright reuses worker wherever possible, which means we can't cleanup browser state in `beforeAll`/`afterAll` hooks as they run at the end of worker. Playwright creates a new worker when test fails, so next test/retry uses fresh state. In our case, we had already connected wallet, and if next test tried to connect wallet again, they will timeout looking for the form. We could've verified & disconnected wallet as a step in each test, but that's not good either - as browser storage & pending API calls can still affect later tests.
I tried various workarounds to run cleanup process in `beforeAll` per file in https://github.com/interledger/web-monetization-extension/pull/864, but nothing gave a clean enough state. …
> test(e2e): avoid sharing browser instance across workers

- src/background/services/monetization.ts
- src/content/services/frameManager.ts
- src/content/services/monetizationLinkManager.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/882
Handles regressions from migrating from `forEach` to `for..of` loops in #814 (thankfully not in stores yet)
- stray return when should've been a continue
- refactor(MonetizationLinkManager): add `onRemovedNode` consistent with `onAddedNode`; replace some `for..of` with Array filter/map
- `addedNodes` in frameManager should've been `removedNodes` ([ref](https://github.com/interledger/web-monetization-extension/pull/882#pullrequestreview-2585790443))
- stronger, more consistent types
> fix: fix regressions caused by `forEach` to `for..of` migration

- src/_locales/en/messages.json
- src/background/services/monetization.ts
- src/pages/popup/components/PayWebsiteForm.tsx
- src/shared/messages.ts
Closes #859.
- Remove amount from payment confirmation message, keeping it limited to: "Thank you for your support".
> fix(popup): remove amount from OTP msg

- src/background/services/wallet.ts
- src/pages/popup/components/Settings/Budget.tsx
- src/pages/popup/pages/Home.tsx
- src/pages/shared/components/ui/Button.tsx
- tests/e2e/connect.spec.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/helpers/common.ts
- tests/e2e/helpers/testWallet.ts
- tests/e2e/pages/popup.ts
- tests/e2e/walletBudget.spec.ts
Part of https://github.com/interledger/web-monetization-extension/issues/610
- Add tests for editing wallet budget (4 budget scenarios)
- Update markup a bit to make testing easier
- Add missing await in background/wallet: `updateBudget`
- Update signature of `connectWallet` test util to make `keyInfo` optional and call-site simpler.
- Add caching to `getWalletInfo` in tests as it gets called by some tests more than once - less network is less noise & more reliability.
> test(e2e): add tests for editing budget

- tests/e2e/connect.spec.ts
- tests/e2e/connectAutoKeyChimoney.spec.ts
- tests/e2e/connectAutoKeyFynbos.spec.ts
- tests/e2e/connectAutoKeyTestWallet.spec.ts
- tests/e2e/fixtures/base.ts
- tests/e2e/fixtures/connected.ts
- tests/e2e/not-monetized.spec.ts
- tests/e2e/overpaying.spec.ts
- tests/e2e/reconnectAutoKeyTestWallet.spec.ts
- tests/e2e/walletBudget.spec.ts
`persistentContext` as identifier was required when we were declaring it on worker scope. With test scope, we can directly call it `context` (overriding default `context`)
i.e. we cannot declare same identifier in different `scope`, but now we use `test` scope only (https://github.com/interledger/web-monetization-extension/pull/879)
Rename `persistentContext` to `context`
> refactor(tests/e2e): rename `persistentContext` to `context`

- .github/workflows/nightly-build.yaml
- .github/workflows/tests-e2e.yml
- docs/TESTING.md
- tests/e2e/.env.example
- tests/e2e/auth.setup.ts
- tests/e2e/env.d.ts
- tests/e2e/helpers/testWallet.ts
Instead of defining vars twice - once in markdown table, and again in env.d.ts, make env.d.ts source of truth. Defining in both places was getting out of hand.
- Update details in env.d.ts
- Create separate top-level interface `TestEnvVars`
- Remove unnecessary `TEST_WALLET_ORIGIN` variable (we can't really use localhost, as so many other dependent variables in test)
> chore(tests/e2e): make `env.d.ts` source of truth for env vars

- src/pages/popup/components/ConnectWalletForm.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/939
This was also seen once in a call with Alex.
- Check latest `walletAddress` form value and validate before submit.
Should do a simplification of this `ConnectWalletForm` component soon. It's feeling very patchy.
> fix(ConnectWalletForm): handle Enter key on wallet address field

- jest.config.ts
- package.json
- pnpm-lock.yaml
- Use `@jgoz/jest-esbuild` to transform ts/tsx files instead of `ts-jest`
- Remove `maxWorkers` restriction from package.json scripts
- Add type checking to jest config
- Fix coverage not picking up files correctly
Running `pnpm test`:
```
Test Suites: 11 passed, 11 total
Tests:       81 passed, 81 total
Snapshots:   0 total
Ran all test suites.
```
```
Before (ts-jest, maxWorkers=2)
Time:        30.298 s
After: with maxWorkers = 2 (and esbuild)
Time:        1.921 s
After: with maxWorkers = 50%  (and esbuild)
Time:        1.867 s
```
```
Before:
Time:        21.182 s
After:
Time:        2.674 s
```
> chore(tests): make tests faster with esbuild, support coverage

- src/background/services/outgoingPaymentGrant.ts
- src/background/services/wallet.ts
Seems counterintuitive, but:
- Helps with https://github.com/interledger/web-monetization-extension/pull/944 to show correct step (when initial create grant fails, and then we switch to adding key).
- Helps with https://github.com/interledger/web-monetization-extension/pull/946 as we open tab at right time, instead of before `createOutgoingPaymentGrant` (as create grant doesn't rely on browser tabs, only complete grant does).
> refactor(bg): split create & complete outgoing payment grant

- src/_locales/en/messages.json
- src/background/services/keyAutoAdd.ts
- src/background/services/wallet.ts
- src/pages/popup/components/ConnectWalletForm.tsx
Fixes https://github.com/interledger/web-monetization-extension/issues/952
Reverts https://github.com/interledger/web-monetization-extension/pull/943
It didn't account for Firefox new tab being opened without a URL.
Removing "abort on tab navigate away" feature in favor of other things we added (like highlight tab, message in popup) and the overall connect timeout (https://github.com/interledger/web-monetization-extension/issues/948) that we'll add soon.
Not handling by adding "new tab" URLs into account, as different browsers can have different "new tab" URLs that we can't keep taking into account. Also, if user has extension for new tab, they can change new tab URL too.
This is a hotfix. We may come back to this in future some day when it's most stable.
> fix(keyAutoAdd): revert abort on tab navigated away

- package.json
- pnpm-lock.yaml
- src/pages/popup/Popup.tsx
- src/pages/popup/components/ErrorKeyRevoked.tsx
- src/pages/popup/components/PayWebsiteForm.tsx
- src/pages/shared/components/FadeInOut.tsx
Closes https://github.com/interledger/web-monetization-extension/issues/817
- Add FadeInOut component
- Takes element props & `as`, to avoid unnecessary nesting (div-soup) in final HTML output
- Remove framer-motion
- Replaced some JSX with Fragment, to avoid too many nesting/whitespace updates
```diff
-  dist/chrome/popup/popup.js                               400.6kb
+  dist/chrome/popup/popup.js                               321.6kb
- chrome.zip   1.02 MB
+ chrome.zip 996.43 KB
```
> perf(popup): remove framer-motion, add custom `FadeInOut`

- .prettierrc.js
- package.json
- pnpm-lock.yaml
This was unused since we introduced Biome. Biome will soon have their own replacement for this https://github.com/biomejs/biome/issues/1274, for this plugin as of now is unused.
Remove the plugin.
> chore(deps): remove prettier-plugin-tailwindcss as unused

- .github/workflows/nightly-build.yaml
https://github.com/interledger/web-monetization-extension/pull/1015#issuecomment-2812224927
Publish nightly build even if tests fail. But still publish it after tests have run.
> chore(ci/nightly): publish build regardless of test status

- src/pages/shared/lib/utils.test.ts
- src/pages/shared/lib/utils.ts
Fixes https://github.com/interledger/web-monetization-extension/issues/1021
- Handle the case of not-3-letter currency by using uppercase-currency as code to prevent crash (in `formatCurrency`, `getCurrencySymbol`).
- Add unit tests
> fix(pages): don't crash when not using 3-letter currencies

- .github/actions/constants.cjs
- .github/actions/get-workflow-artifacts.cjs
Badges not loading:
- Create shields.io badge URL properly
- Some TypeScript improvements, cleanups, less string manipulation
- Improve alt text for the badge.
**To reviewer**: You won't see them loading in this PR either, as CI checks out `main` branch when running badge-generation script, instead of PR branch.
> chore(ci/build-previews): encode shields.io badge URL so it loads

- src/background/services/wallet.ts
- src/shared/types.ts
Useful with https://github.com/interledger/web-monetization-extension/issues/1029
Some wallet URLs have redirects, and the resulting `resourceServer` could be something that corresponds to a different wallet as well.
With this info stored, we can:
- help distinguish those redirect wallets (MMAON, ilp.dev) from their _managing wallets_
- display the wallet address that user entered in UI - like UI showing ilp.dev instead of ilp.interledger.cards address (not done yet)
- Store `walletAddressUrl` as `walletAddress.url` in extension storage.
- The `url` property isn't part of standard [`WalletAddress` response](https://openpayments.dev/apis/wallet-address-server/operations/get-wallet-address/), so it's safe to add to storage within this object. 
- The field is marked optional as it doesn't …
> fix(bg/storage): store user provided wallet URL as well

- src/background/services/background.ts
On browser start, there was a warning that the polyfill script was already registered.
Also, this warning was incorrectly included in the "Content script execution world `MAIN` not supported by your browser" warning.
- Set `persistAcrossSessions: false` to prevent error in first place and for consistency with other content scripts.
- Silence duplicate script error (different browsers may have different error message)
> fix(background): avoid duplicate polyfill script warning

- src/background/services/paymentSession.ts
Part of https://github.com/interledger/web-monetization-extension/issues/976
Extracted from https://github.com/interledger/web-monetization-extension/pull/1046
- When a new link tag is added, we want to keep using older `minSendAmount`, even if the `adjustAmount` may change due to splits. `adjustAmount` resulting rate is >= `minSendAmount`, so it makes sense to find `minSendAmount` first, and not find it ever again.
Known existing issues (discovered while working this out):
- Currency fluctuations can change this `minSendAmount` in future. In that case, we'd need to probe/`findMinSendAmount` again.
- Exponential probing is likely not the best approach. (Raw thoughts follow) I wonder if we can use currency conversion and then binary search or two-way search some values (specially relevant …
> fix(PaymentSession): find `minSendAmount` independent of rate

- src/background/services/monetization.ts
- src/background/services/paymentSession.ts
Part of https://github.com/interledger/web-monetization-extension/issues/976
The goal is to efficiently find the `minSendAmount` for a `PaymentSession`.
Reuse PaymentSession instead of starting a new one.
<details>
<summary>Original PR summary</summary>
- In the first commit (https://github.com/interledger/web-monetization-extension/pull/1046/commits/e4a8ae51ec998fe3d2829198d429d58e2c4b4088), it won't have the desired effect, as we have an `AbortSignal` that makes the probing restart.
- In the next commit (https://github.com/interledger/web-monetization-extension/pull/1046/commits/c5de59ff43e6572a62637b7099096d0536062a7a), we replace `adjustAmount(rate)` with `findMinSendAmount()` (which is independent of rate). Extracted into [1048](https://github.com/interledger/web-monetization-extensio …
> perf(bg/monetization): reuse `PaymentSession` when link added

- src/background/services/paymentSession.ts
- src/background/utils.ts
- src/shared/helpers/misc.ts
Part of https://github.com/interledger/web-monetization-extension/issues/976
When sending cross currency payments (specially from higher to lower exchange rate, e.g. MXN to USD (0.19MXN = 0.01USD)), make use of exchange rate and use it as the starting point for probing.
When sending from MXN to USD, there's now a single (1) quote instead of 6.
This won't be needed when we get with https://github.com/interledger/rafiki/pull/3411 available across wallets.
This also gives us a more accurate minSendAmount, as otherwise with current exponential probing, we may end up trying to send 1,2,4,8,16,32 units, instead of something in between (19 here).
The exchange rates are cached for 15min as we don't want to fetch them for each session.
> perf(bg/PaymentSession): fewer quote requests using exchange rate

- src/background/container.ts
- src/background/services/monetization.ts
- src/background/services/paymentSession.ts
- src/shared/logger.ts
Found useful when working on payment streams.
Create an instance of logger per `PaymentSession`.
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/ea78af68-09ee-4060-b5d9-e72510976b93) | ![image](https://github.com/user-attachments/assets/78492344-3ac7-43c2-a60d-562193a18ad2) |
Might make `requestId` shorter in future 😄
> fix(bg/paymentSession): prefix logs per instance

- src/pages/popup/components/Settings/RateOfPay.tsx
- src/pages/popup/lib/store.ts
- src/shared/messages.ts
- src/shared/types.ts
Sometimes we ended up storing rate as a string containing decimals, which crashed when we tried to convert it to `BigInt(rateOfPay)`.
- `Math.round()` rate of pay when parsing from the input, so there are no decimals in it.
- Update types to make it clearer that we want a big-int like string (`AmountValue`) there, instead of any string.
> fix(Settings/RateOfPay): ensure `AmountValue` is used as rate

- src/background/services/paymentManager.ts
- src/background/services/paymentSession.ts
Extracted from https://github.com/interledger/web-monetization-extension/pull/1066
- Made some constructor args `public readonly`, so we don't need to define their getters.
- Simplified `sendMonetizationEvent` to not require `requestId` in payload.
> refactor(paymentSession): remove some getters, simplify emit

- .github/workflows/nightly-build.yaml
- .github/workflows/release-preview.yml
- .github/workflows/release-stable.yml
Action failing to upload files: [run 1](https://github.com/interledger/web-monetization-extension/actions/runs/15561155826/job/43813517943), [run 2](https://github.com/interledger/web-monetization-extension/actions/runs/15561178444/job/43813594812).
See https://github.com/softprops/action-gh-release/issues/627, https://github.com/softprops/action-gh-release/issues/628
Lock version to last working version.
> chore(ci): lock `softprops/action-gh-release` action

- src/background/config.ts
- src/background/services/monetization.ts
- src/background/services/storage.ts
- src/background/services/wallet.ts
- src/pages/popup/components/Settings/RateOfPay.tsx
- src/shared/helpers/wallet.ts
- src/shared/types.ts
Closes https://github.com/interledger/web-monetization-extension/issues/1084
Helps with https://github.com/interledger/web-monetization-extension/issues/1082
- Remove `minRateOfPay` from code, storage and UI.
- In Settings > Rate of Pay, set min to 1 unit
- As we're doing a storage structure migration, make `WalletInfo.url` as required. Make it same as `WalletAddress.id` when not available. Helps with [#1082](https://github.com/interledger/web-monetization-extension/issues/1082).
- Return `WalletInfo` from `getWalletInformation` (instead of `WalletAddress`)
> fix: remove `minRateOfPay`, make `WalletInfo.url` required

- esbuild/dev.ts
- src/background/services/background.ts
- src/background/services/monetization.ts
- src/background/services/tabEvents.ts
- src/background/services/tabState.ts
- src/content/__tests__/monetizationLinkManager.test.ts
- src/content/services/monetizationLinkManager.ts
- src/shared/messages.ts
On page refreshes/unloads, we were not clearing paymentManager correctly. We made use of individual `STOP_MONETIZATION` events to destroy/reset `paymentManger`, which was flaky, specially if a pause was emitted after stop, leading to state not being reset correctly.
- Add a `PAGE_HIDE` message (only from top-level frame) to so we can use it to destroy `paymentManager` on page unload/refresh.
- Ensure `removeSession` works correctly, by not passing it incorrect `frameId` when iframes were involved (we always ended up passing `frameId = 0` from top frame.
- Prevent pause-all from being called after pagehide.
- Add some more logging.
> fix: better handle state clearing on page refresh/unload

- src/pages/app/pages/PostInstall.tsx
- src/pages/popup/pages/ConnectWallet.tsx
- src/shared/messages.ts
https://github.com/interledger/web-monetization-extension/pull/1073 added this message, but we were doing fetches from frontend directly.
- Use the `GET_CONNECT_WALLET_ADDRESS_INFO` message
- Add a util `getResponseOrThrow` to throw when `Response` isn't successful.
> fix: get connect wallet info via background only

- tests/e2e/connectAutoKeyChimoney.spec.ts
Either Chimoney improved it, or https://github.com/interledger/web-monetization-extension/pull/1125 helped.
Another E2E test to pass!
> test(e2e/connectAutoKeyChimoney): don't require login on consent

- tests/e2e/fixtures/base.ts
- tests/e2e/multiple.spec.ts
- tests/e2e/reconnectAutoKeyTestWallet.spec.ts
https://github.com/interledger/web-monetization-extension/pull/1066 updated continuous payment logic, but our E2E tests lagged behind.
Also had to update playground a bit to make tests more reliable: https://github.com/WICG/webmonetization/pull/545.
- Update E2E tests for multiple wallet addresses' continuous payments
- Also mark a test (`reconnectAutoKeyTestWallet.spec.ts`) as slow, as it can take upto ~40s now, instead of default 30s.
> test(e2e): update expected payment flow for multiple links

- README.md
- docs/INSTALL.MD
- Move Install instructions out of README, and into docs/INSTALL.md
- Add Safari to install instructions
- Add more details to install instructions
- Change format of Commands section in README
- Instead of table, use bullet lists
- Add more helpful commands and their descriptions.
> docs: improve README, INSTALL instructions

- .github/actions/tests-e2e-filter.cjs
- .github/workflows/tests-e2e.yml
- package.json
- pnpm-lock.yaml
To make sure E2E test failures aren't easily ignored.
- Run E2E tests automatically on each PR from repo maintainers (or those with write access)
- Run only for Chromium to keep things lighter
- Can still run all tests with `test-e2e` review comment from maintainers for other cases
- Add `.github/actions/tests-e2e-filter.cjs` helper as a "Prepare" step to detect which tests to run, and if should run tests.
- Can improve this in future further to only run specific tests based on changed files, review comment body details etc.
- Had to dynamically generate `matrix` as we cannot use matrix with `if` on job-level.
> chore(ci/test-e2e): run on each PR from maintainers as well

- .gitignore
- tests/e2e/fixtures/helpers.ts
When re-running tests locally, we've to go through the auth.setup step each time, as the `test-results` folder gets cleared on each test run, making repetitive testing slower locally.
Store auth cookies in `.auth` folder, and store that data weekly (`yyyy` followed by week number of the year (`II`)).
> chore(tests/e2e): save cookies outside of `test-results` dir

- src/background/services/monetization.ts
- src/background/services/paymentManager.ts
Reported by Chimoney that they were often getting "taking too long" message.
If making the payment took longer, we had less time for polling afterwards. Other wallets were making payments faster (maybe faster sandbox account), so it wasn’t caught.
Aside: maybe the timeout earlier meant user facing timeout after they click the pay button - it included the payment + polling. Or, it was regressed at some stage.
Might relate to https://github.com/interledger/web-monetization-extension/issues/877, but not enough data in that issue.
Start polling timeout after making the payment, so the polling timeout does what its name says.
> fix(one-time-payment): start polling timeout after making payment

- src/_locales/en/messages.json
- src/background/services/background.ts
- src/background/services/openPayments.ts
- src/background/services/wallet.ts
- src/pages/popup/components/ErrorKeyRevoked.tsx
- src/pages/popup/components/Settings/WalletInformation.tsx
- src/pages/popup/pages/ErrorKeyRevoked.tsx
- src/shared/messages.ts
Closes https://github.com/interledger/web-monetization-extension/issues/1162
When there are issues with disconnecting wallet, show user an error and allow force disconnecting.
The error is only shown when disconnecting from WalletInfo page. On keyRevoked error page, I decided to enable `force` by default to not add new UI.
Note: When we do a force disconnect, the access token isn't revoked from wallet end. We just delete it from our local storage (forget about it), so the user can move forward with their life. Hence, there can be dangling grants shown in wallet UI.
---
I considered adding a job queue for when things fail and doing them later on, but it had issues with authentication (in case client changed after a reconnect etc.). So, decided to keep it simple.
> fix: support force disconnect wallet in case of error

- src/background/services/wallet.ts
When I accidentally delete keys (during dev), the extension is forever stuck in missing keys state. The key storage gets corrupted beyond repair on updates.
Generate fresh pair of keys during connect process if not already present in storage.
> fix(bg/wallet): generate keys if not present before connecting

- src/_locales/en/messages.json
- src/background/services/background.ts
- src/background/services/monetization.ts
- src/background/services/storage.ts
- src/pages/app/App.tsx
- src/pages/app/lib/store.ts
- src/pages/app/pages/PostInstall.tsx
- src/pages/app/pages/PostInstallConsent.tsx
- src/pages/app/pages/index.tsx
- src/pages/popup/Popup.tsx
- src/pages/popup/pages/ConsentRequired.tsx
- src/pages/popup/pages/Home.tsx
- src/pages/popup/pages/index.tsx
- src/pages/shared/components/Icons.tsx
- src/pages/shared/style.css
- src/shared/helpers/misc.ts
- src/shared/messages.ts
- src/shared/types.ts
- tailwind.config.ts
- tests/e2e/fixtures/helpers.ts
Closes https://github.com/interledger/web-monetization-extension/issues/1189
> feat(PostInstall): add consent screen about data sharing
